name: GoldmanChunks
main: lee.code.chunks.GoldmanChunks
version: ${project.version}
api-version: 1.16
author: Lee
depend: [GoldmanEssentials, RedisCache]
commands:
  chunk:
    description: Main plugin command.
    permission: chunk.command.chunk
    aliases: [c]
  adminchunk:
    description: Admin chunk command.
    permission: mychunks.adminchunk
    aliases: [ac]