name: GoldmanChunks
main: lee.code.chunks.GoldmanChunks
version: ${project.version}
api-version: 1.16
author: Lee
commands:
  chunk:
    description: Main plugin command.
    permission: chunk.command.use
    aliases: [c]
  adminchunk:
    description: Admin chunk command.
    permission: mychunks.admin
    aliases: [ac]