name: MyChunks
main: lee.code.mychunks.MyChunks
version: ${project.version}
api-version: 1.16
author: Lee
commands:
  chunk:
    description: Main plugin command.
    permission: mychunks.command.use
    aliases: [c]
  adminchunk:
    description: Admin chunk command.
    permission: mychunks.admin
    aliases: [ac]