package lee.code.chunks.lists;

import lee.code.core.util.bukkit.BukkitUtils;
import lombok.AllArgsConstructor;
import lombok.Getter;
import net.kyori.adventure.text.Component;

@AllArgsConstructor
public enum Lang {
    PREFIX("&e&lChunks &6➔ &r"),
    TELEPORT("&eWhooosh!"),
    TRUE("&atrue"),
    FALSE("&cfalse"),
    ON("&2&lON"),
    OFF("&c&lOFF"),
    USAGE("&6&lUsage: &e{0}"),
    MESSAGE_HELP_DIVIDER("&e▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"),
    MESSAGE_HELP_TITLE("                      &6-== &a&l&nChunk Help&r &6==-"),
    MESSAGE_HELP_SUB_COMMAND("&3{0}&b. &e{1}"),
    MESSAGE_HELP_SUB_COMMAND_HOVER("&6{0}"),
    ERROR_NO_PERMISSION("&cYou sadly do not have permission for this."),
    ERROR_NO_CLAIM_PERMISSION_ADMIN_CHUNK("&4&lAdmin Chunk"),
    ERROR_NO_CLAIM_PERMISSION("&6&lTrusted&7: {0} &7| {1} &7| &6&lOwner&7: &2{2}"),
    ERROR_CLAIMED("&cThis chunk has already been claimed by &6{0}&c."),
    ERROR_CLAIMED_OWNER("&cYou already own this chunk."),
    ERROR_ADMIN_CLAIMED("&cSadly this chunk has already been claimed as a &4&lAdmin &cchunk."),
    ERROR_COMMAND_ADMIN_UNCLAIM("&cThe chunk &e(&b{0}&e) &cis not owned by anyone, you need to stand on a chunk owned by a player."),
    ERROR_COMMAND_UNCLAIM_WHILE_AUTO_CLAIM("&cYou can't unclaim chunks while auto-claim is enabled."),
    ERROR_COMMAND_UNCLAIM_OWNER("&cThis chunk is owned by &6{0}&c, you need to be the owner to unclaim it."),
    ERROR_COMMAND_UNCLAIMED_NOT_CLAIMED("&cThis chunk is not claimed so you can not unclaim it."),
    ERROR_COMMAND_AUTO_CLAIM("&cYou moved outside of the chunks around the last group you auto claimed so auto claim has been disabled."),
    ERROR_COMMAND_ABANDONALLCLAIMS_NO_CLAIMS("&cYou have no claimed chunks so nothing was unclaimed."),
    ERROR_COMMAND_CLAIM_MAXED("&cYou have reached the max amount of chunks you can claim at this time &e(&2{0}&7/&2{1}&e)&c."),
    ERROR_COMMAND_WORLD_SUPPORT("&cYou can't claim chunks in this world."),
    ERROR_COMMAND_BUY_NOT_CLAIMED("&cThe chunk &e(&b{0}&e) &cis not currently claimed so you can't buy it. Use /chunk claim."),
    ERROR_COMMAND_BUY_NOT_FOR_SALE("&cThe chunk &e(&b{0}&e) &cis not currently for sale. You can ask &6{1} &cif they want to sell it."),
    ERROR_COMMAND_BUY_OWNER("&cYou can't buy your own chunk. You already own it..."),
    ERROR_COMMAND_BUY_BALANCE("&cYou need &6${0} &cto buy the chunk &e(&b{1}&e) &cfrom &6{2} &cbut you only have &6${3}&c."),
    ERROR_COMMAND_TRUSTED_NOT_CLAIMED("&cThe chunk must be claimed to check all the trusted users."),
    ERROR_COMMAND_TRUSTED_ADMIN_CHUNK("&cAdmin chunks can not have trusted users."),
    ERROR_COMMAND_TRUST_ALREADY_ADDED("&cThe player &6{0} &cis already added to your trusted list on chunk &e(&b{1}&e)&c."),
    ERROR_COMMAND_TRUST_NO_TARGET_PLAYER("&cYou need to enter a player you want to trust to the chunk you're standing on."),
    ERROR_COMMAND_TRUSTALL_ALREADY_ADDED("&cThe player &6{0} &cis already added to your global trusted list."),
    ERROR_COMMAND_TRUSTALL_NO_TARGET_PLAYER("&cYou need to enter a player you want to trust globally."),
    ERROR_TELEPORT_UNSAFE("&cSadly there wasn't a safe place to teleport so it was canceled."),
    ERROR_TELEPORT_NOT_OWNER("&cYou are not the owner of the chunk &e(&b{0}&e)&c, teleport canceled."),
    ERROR_TELEPORT_NOT_CLAIMED("&cThe chunk &e(&b{0}&e)&c is not currently claimed, teleport canceled."),
    ERROR_COMMAND_UNTRUST_PLAYER_NOT_TRUSTED("&cThe player &6{0} &cis not trusted to the chunk &e(&b{1}&e)&c."),
    ERROR_COMMAND_UNTRUSTALL_PLAYER_NOT_TRUSTED("&cThe player &6{0} &cis not listed on your global trust list."),
    ERROR_COMMAND_UNTRUSTALL_NO_TARGET_PLAYER("&cYou need to enter a player you want to untrust globally."),
    ERROR_COMMAND_UNTRUST_NOT_CHUNK_OWNER("&cYou need to be the owner of the chunk to untrust a player from it."),
    ERROR_COMMAND_UNTRUST_NO_TARGET_PLAYER("&cYou need to enter a player you want to untrust from the chunk you're standing on."),
    ERROR_COMMAND_BLOCK_ADD_NO_TARGET_PLAYER("&cYou need to enter a player you want to block from all your claimed chunks."),
    ERROR_COMMAND_BLOCK_REMOVE_NO_TARGET_PLAYER("&cYou need to enter a player you want to remove from your blocked list."),
    ERROR_COMMAND_BLOCK_ALREADY_BLOCKED("&cThe player &6{0} &cis already on your blocked list."),
    ERROR_COMMAND_BLOCK_NOT_BLOCKED("&cThe player &6{0} &cis not on your blocked list."),
    ERROR_COMMAND_BLOCK_SELF("&cYou can't block yourself from your own chunks."),
    ERROR_LIST_PAGE_NOT_NUMBER("&cThe input &6{0} &cis not a number. &a&lUse&7: &e(1)"),
    ERROR_COMMAND_ADMIN_BONUS_CLAIMS_AMOUNT("&cThe input &6{0} &cis not a number."),
    ERROR_COMMAND_ADMIN_BONUS_CLAIMS_ARG_2("&cYou need to specify if you want to add, remove or set a players bonus claims."),
    ERROR_COMMAND_ADMIN_BONUS_CLAIMS_ARG_3("&cYou need to specify a player and an amount you want to give them."),
    ERROR_COMMAND_ADMIN_BONUS_CLAIMS_ARG_4("&cYou need to specify an amount of bonus claims."),
    ERROR_COMMAND_ADMIN_ARGS("&cYou need to specify which admin command you would like to run."),
    ERROR_COMMAND_ADMIN_WRONG_ARG("&cThe admin arg &6{0} &cis not a valid option."),
    ERROR_COMMAND_SETPRICE_NOT_CLAIMED("&cThe chunk you're currently standing on is not claimed."),
    ERROR_COMMAND_SETPRICE_ADMIN_CHUNK("&cYou can not sell admin chunks."),
    ERROR_COMMAND_SETPRICE_NOT_OWNER("&cThe chunk you're currently standing on is owned by &6{0} &cand only they are able to put a chunk up for sale."),
    ERROR_COMMAND_SETPRICE_MAX_VALUE("&cYou can only sell a chunk for a max of ${0}&c."),
    ERROR_COMMAND_SETPRICE_NOT_NUMBER("&cThe input &b{0} &cis not a accepted value. You need to input a sell price, decimals are not supported."),
    ERROR_COMMAND_SETPRICE_NO_NUMBER("&cYou need to input a number for how much you would like to sell the chunk you're standing on. Keep in mind decimals are not supported."),
    ERROR_COMMAND_FLY_NOT_OWNER("&cYou must be the owner or trusted on the chunk you're standing on to use this command."),
    ERROR_COMMAND_FLY_OUTSIDE_OF_CLAIM("&cYour fly has been toggled off due to going outside of claimed or trusted chunks."),
    ERROR_COMMAND_FLY_PVP("&cYour fly has been toggled off due to going into battle with another player."),
    ERROR_PREVIOUS_PAGE("&7You are already on the first page."),
    ERROR_NEXT_PAGE("&7You are on the last page."),
    ERROR_COMMAND_MANAGE_NOT_CHUNK_OWNER("&cYou need to be standing on a chunk you own to open this menu."),
    ERROR_COMMAND_ADMIN_MANAGE_NOT_ADMIN_CHUNK("&cYou need to be standing on a admin chunk to open this menu."),
    ERROR_PLAYER_NOT_ONLINE("&cThe player &6{0} &cis not online."),
    ERROR_COMMAND_SELECTION_NO_CHUNKS_SELECTED("&cYou don't currently have any chunks selected."),
    ERROR_COMMAND_TRUST_NOT_OWNER("&cYou need to be the owner of this chunk to trust a player to it."),
    ERROR_COMMAND_TRUST_OWNER("&cYou can't trust yourself to a chunk you own."),
    ERROR_NOT_A_CONSOLE_COMMAND("&cThis is not a console command."),
    ERROR_PLAYER_NOT_FOUND("&cThe player &6{0} &chas never logged into this server."),
    ERROR_BLOCKED_ENTER("&cThe player &6{0} &chas blocked you from entering their claimed chunks!"),
    ERROR_BLOCKED_TELEPORT("&cThe player &6{0} &chas blocked you from teleporting to their claimed chunks, teleportation canceled."),
    COMMAND_RELOAD_SUCCESSFUL("&aThe plugin has been reloaded."),
    COMMAND_CLAIM_SUCCESSFUL("&aYou successfully claimed the chunk &e(&b{0}&e)&a! You now have &e(&2{1}&7/&2{2}&e) &aclaims."),
    COMMAND_BUY_SUCCESSFUL("&aYou successfully bought the chunk &e(&b{0}&e)&a for &6${1}&a from &6{2}&a! You now have &e(&2{3}&7/&2{4}&e) &aclaims."),
    COMMAND_BUY_SUCCESSFUL_OWNER("&aThe player &6{0} &abought your chunk &e(&b{1}&e)&a for &6${2}&a! You now have &e(&2{3}&7/&2{4}&e) &aclaims."),
    COMMAND_ABANDONALLCLAIMS_SUCCESSFUL("&aYou successfully unclaimed all your chunks. You now have &e(&2{0}&7/&2{1}&e) &aclaims."),
    COMMAND_UNCLAIM_SUCCESSFUL("&aYou successfully unclaimed the chunk &e(&b{0}&e)&a!"),
    COMMAND_AUTO_CLAIM_DISABLED("&aYou successfully &cdisabled &aauto claim."),
    COMMAND_AUTO_CLAIM_ENABLED("&aYou successfully &2enabled &aauto claim!"),
    COMMAND_TRUST_ADDED_PLAYER("&aYou successfully added the player &6{0} &ato your trusted list on chunk &e(&b{1}&e)&a!"),
    COMMAND_UNTRUST_REMOVED_PLAYER("&aYou successfully removed the player &6{0} &afrom your trusted list on chunk &e(&b{1}&e)&a."),
    COMMAND_BLOCK_ADDED_PLAYER("&aYou successfully added the player &6{0} &ato your blocked list!"),
    COMMAND_BLOCK_ADDED_ON_CHUNK("&cThe player &6{0} &chas blocked you from entering their claimed chunks so you have been teleported to spawn."),
    COMMAND_BLOCK_REMOVED_PLAYER("&aYou successfully removed the player &6{0} &afrom your blocked list!"),
    COMMAND_ADMIN_BYPASS_ENABLED("&aAdmin claim bypass is now &2enabled&a!"),
    COMMAND_ADMIN_BYPASS_DISABLED("&aAdmin claim bypass is now &cdisabled&a."),
    COMMAND_ADMIN_SELECTION_SETTING_UPDATE("&3You successfully set &e{0} &3to {1} &3for &4{2} &3admin chunks."),
    COMMAND_ADMIN_SELECTION_FIRST("&aYou successfully selected the chunk &e(&b{0}&e)&a! Now run the command &6/adminchunk selection &aagain to select all chunks between this selected chunk."),
    COMMAND_ADMIN_SELECTION_SUCCESSFUL("&aYou successfully selected &4{0} &achunks!"),
    COMMAND_ADMIN_SELECTION_CLEAR_SUCCESSFUL("&aYou successfully cleared your chunk selection!"),
    COMMAND_ADMIN_CLAIM_CHUNK("&aYou successfully claimed the chunk &e(&b{0}&e)&a as a admin chunk."),
    COMMAND_ADMIN_CLAIM_SELECTION("&aYou successfully claimed &4{0} &aadmin chunks!"),
    COMMAND_ADMIN_UNCLAIM_SELECTION("&aYou successfully unclaimed &4{0} &aadmin chunks!"),
    COMMAND_ADMIN_UNCLAIM("&aYou successfully unclaimed chunk &e(&b{0}&e) &afrom &6{1}&a."),
    COMMAND_ADMIN_UNCLAIM_CHUNK("&aYou successfully unclaimed the admin chunk &e(&b{0}&e)&a."),
    COMMAND_ADMIN_UNCLAIMALL("&aYou successfully unclaimed all the chunks the player &6{0} &aowned."),
    COMMAND_ADMIN_BONUS_CLAIMS_ADD("&aSuccessfully added &2{0} bonus claims &ato player &6{1}&a."),
    COMMAND_ADMIN_BONUS_CLAIMS_REMOVE("&aSuccessfully removed &2{0} bonus claims &afrom player &6{1}&a."),
    COMMAND_ADMIN_BONUS_CLAIMS_SET("&aSuccessfully set &2{0} bonus claims &afor player &6{1}&a."),
    COMMAND_UNTRUSTALL_REMOVED_PLAYER("&aYou successfully removed the player &6{0} &afrom your global trusted list."),
    COMMAND_TRUSTALL_ADDED_PLAYER("&aYou successfully added the player &6{0} &ato your global trusted list!"),
    COMMAND_SETPRICE_SUCCESSFUL("&aYou successfully set your chunk &e(&b{0}&e) &aat a sell price of &6${1}&a!"),
    COMMAND_SETPRICE_REMOVE_SUCCESSFUL("&aYour chunk &e(&b{0}&e) &ais now no longer for sale."),
    NEXT_PAGE_TEXT("&2&lNext &a&l>>--------"),
    EMOJIS_NEXT_PAGE_TEXT("&2&lNext &a&l>>-----------"),
    EMOJIS_PREVIOUS_PAGE_TEXT("&a&l-----------<< &2&lPrev"),
    PREVIOUS_PAGE_TEXT("&a&l--------<< &2&lPrev"),
    PAGE_SPACER(" &e| "),
    NEXT_PAGE_HOVER("&6&lNext Page"),
    PREVIOUS_PAGE_HOVER("&6&lPrevious Page"),
    COMMAND_INFO_HEADER("&a--------- &7[ &2&lChunk Info &7] &a---------"),
    COMMAND_INFO_LINE_1("&2&lChunk Owner&7: &6{0}"),
    COMMAND_INFO_LINE_2("&2&lChunk Coordinate&7: &b{0}"),
    COMMAND_INFO_LINE_3("&2&lChunk Price&7: &6${0}"),
    COMMAND_INFO_FOOTER("&a---------------------------------"),
    COMMAND_MAP_HEADER("&a--------- &7[ &2&lChunk Map &7] &a---------"),
    COMMAND_MAP_KEY_HEADER("&a---------- &7[ &2&lMap Key &7] &a----------"),
    COMMAND_MAP_LINE_1(" {0}  &6&lYOU&7: &9■ &6&lCLAIMED&7: &2■ &6&lWILD&7: &7■"),
    COMMAND_MAP_LINE_2(" {0}     &6&lTRUSTED&7: &a■ &6&lOWNED&7: &c■"),
    COMMAND_MAP_LINE_3(" {0}              &6&lADMIN&7: &4■"),
    COMMAND_MAP_FOOTER("&a--------------------------------"),
    COMMAND_BLOCKED_HEADER("&a------- &6[ &2&lBlocked Players &6] &a-------"),
    COMMAND_BLOCKED_LINE("&3{0}&b. &6{1}"),
    COMMAND_BLOCKED_NONE_BLOCKED("&cYou do not currently have any players blocked."),
    COMMAND_TRUSTED_HEADER("&a-------------- &6[ &2&lTrusted Players &6] &a--------------"),
    COMMAND_TRUSTED_LINE_1("&6&lGlobal Trusted&7: &a{0}"),
    COMMAND_TRUSTED_LINE_2("&6&lChunk Trusted&7: &a{0}"),
    COMMAND_TRUSTED_FOOTER("&a-------------------------------------------------"),
    COMMAND_MAX_CLAIMS_HEADER("&a----------------- &6[ &2&lClaim Info &6] &a-----------------"),
    COMMAND_MAX_CLAIMS_LINE_1("&6&lDefault Claims&7: &2{0}"),
    COMMAND_MAX_CLAIMS_LINE_2("&6&lBonus Claims&7: &2{0}"),
    COMMAND_MAX_CLAIMS_LINE_3("&6&lClaimed&7: &2{0}"),
    COMMAND_MAX_CLAIMS_LINE_4("&6&lTime Played&7: &e{0}"),
    COMMAND_MAX_CLAIMS_LINE_5("&6&lAccrued Timer&7: &2{0} claim every {1} &2played"),
    COMMAND_MAX_CLAIMS_LINE_6("&6&lAccrued Claims&7: &2{0}&7/&2{1}"),
    COMMAND_MAX_CLAIMS_LINE_7("&6&lTotal Claims&7: &2{0}&7/&2{1}"),
    COMMAND_MAX_CLAIMS_FOOTER("&a------------------------------------------------"),
    COMMAND_FLY_TOGGLE_SUCCESSFUL("&aYour fly has been toggled {0}&a."),
    MENU_ADMIN_CHUNK_SETTINGS_TITLE("&4&lAdmin Chunk Settings"),
    MENU_CHUNK_MANAGER_TITLE("&c&lChunk Manager"),
    MENU_PLAYER_CHUNKS_TITLE("&2&lClaimed Chunks &8Page {0}"),
    MENU_GENERAL_CHUNK_SETTINGS_TITLE("&e&lGeneral Chunk Settings"),
    MENU_TRUSTED_TITLE("&2&lTrusted Chunk Settings"),
    MENU_GLOBAL_TRUSTED_TITLE("&2&lTrusted Global Settings"),
    MENU_PLAYER_CHUNKS_ITEM_NAME("&b&l&n{0}"),
    ITEM_SETTINGS_BUILD_NAME("&6&lBuild&7: {0}"),
    ITEM_SETTINGS_BREAK_NAME("&6&lBreak&7: {0}"),
    ITEM_SETTINGS_INTERACT_NAME("&6&lInteract&7: {0}"),
    ITEM_SETTINGS_PVE_NAME("&6&lPvE&7: {0}"),
    ITEM_SETTINGS_PORTAL_NAME("&6&lUse Portals&7: {0}"),
    ITEM_SETTINGS_MONSTER_SPAWNING_NAME("&6&lMonster Spawning&7: {0}"),
    ITEM_SETTINGS_EXPLOSIONS_NAME("&6&lExplosions&7: {0}"),
    ;

    @Getter private final String string;

    public String getString(final String[] variables) {
        String value = BukkitUtils.parseColorString(string);
        if (variables == null) return value;
        else if (variables.length == 0) return value;
        for (int i = 0; i < variables.length; i++) value = value.replace("{" + i + "}", variables[i]);
        return BukkitUtils.parseColorString(value);
    }

    public Component getComponent(String[] variables) {
        String value = string;
        if (variables == null || variables.length == 0) return BukkitUtils.parseColorComponent(value);
        for (int i = 0; i < variables.length; i++) value = value.replace("{" + i + "}", variables[i]);
        return BukkitUtils.parseColorComponent(value);
    }
}